#!/bin/bash
# Complete deployment guide with commands

echo "=== CodeRunner - Complete Deployment Guide ==="
echo ""
echo "This script shows the exact commands needed to deploy both frontend and backend to Vercel."
echo ""
echo "Prerequisites:"
echo "  - GitHub account with repository pushed"
echo "  - Vercel account (https://vercel.com)"
echo "  - Node.js 18+ installed locally"
echo ""
echo "=== STEP 1: Prepare your code ==="
echo ""
echo "1. Make sure all code is committed to GitHub:"
echo ""
echo "  cd /path/to/codeRunner"
echo "  git add ."
echo "  git commit -m 'Prepare for Vercel deployment'"
echo "  git push origin main"
echo ""
echo "2. Verify folder structure:"
echo "  ."
echo "  ├── Backend/      (Node.js, will deploy to Vercel)"
echo "  ├── Frontend/     (Angular, will deploy to Vercel)"
echo "  └── README.md"
echo ""
echo ""
echo "=== STEP 2: Deploy Backend to Vercel ==="
echo ""
echo "1. Go to https://vercel.com/new"
echo "2. Click 'Import Git Repository'"
echo "3. Select your GitHub repository"
echo "4. Configure:"
echo "   - Project Name: coderunner-backend (or your choice)"
echo "   - Root Directory: Backend"
echo "   - Framework: Other"
echo "5. Click Deploy"
echo "6. After deployment completes, you'll get a URL like:"
echo "   https://coderunner-backend-xyz123.vercel.app"
echo ""
echo "7. Copy this URL (you'll need it for the frontend)"
echo ""
echo ""
echo "=== STEP 3: Update Frontend Configuration ==="
echo ""
echo "1. Edit Frontend/src/environments/environment.ts:"
echo ""
cat << 'EOF'
export const environment = {
    production: true,
    apiUrl: 'https://coderunner-backend-xyz123.vercel.app'  // <- Paste your backend URL here
};
EOF
echo ""
echo ""
echo "2. Edit Frontend/src/environments/environment.prod.ts with the same URL"
echo ""
echo "3. Commit and push:"
echo ""
echo "  git add Frontend/src/environments/"
echo "  git commit -m 'Update backend URL for Vercel'"
echo "  git push origin main"
echo ""
echo ""
echo "=== STEP 4: Deploy Frontend to Vercel ==="
echo ""
echo "1. Go to https://vercel.com/new"
echo "2. Click 'Import Git Repository'"
echo "3. Select your GitHub repository"
echo "4. Configure:"
echo "   - Project Name: coderunner-frontend (or your choice)"
echo "   - Root Directory: Frontend"
echo "   - Framework: Angular"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist/code-runner"
echo "5. Click Deploy"
echo "6. After deployment, you'll get a URL like:"
echo "   https://coderunner-frontend-xyz123.vercel.app"
echo ""
echo ""
echo "=== STEP 5: Test Everything Works ==="
echo ""
echo "1. Open your frontend URL in a browser"
echo "2. Write some code:"
echo ""
cat << 'EOF'
# Python example
print("Hello from Vercel!")

# JavaScript example
console.log("Hello from Vercel!");

# C++ example
#include <iostream>
int main() {
    std::cout << "Hello from Vercel!" << std::endl;
    return 0;
}
EOF
echo ""
echo "3. Click 'Run' and you should see output"
echo ""
echo ""
echo "=== STEP 6: Share with the World! 🎉 ==="
echo ""
echo "Your live compiler URLs:"
echo "  Frontend: https://coderunner-frontend-xyz123.vercel.app"
echo "  Backend:  https://coderunner-backend-xyz123.vercel.app"
echo ""
echo "Add to:"
echo "  - Your GitHub profile README"
echo "  - Your portfolio website"
echo "  - Your resume/CV"
echo ""
echo ""
echo "=== Troubleshooting ==="
echo ""
echo "Backend returns 500 error:"
echo "  → Check Vercel dashboard → Deployments → Logs"
echo "  → Ensure Python/Node/G++ are pre-installed (they should be)"
echo ""
echo "Frontend can't reach backend:"
echo "  → Open browser DevTools (F12)"
echo "  → Check for CORS errors in Console"
echo "  → Verify environment.ts has correct URL (no trailing slash)"
echo ""
echo "Code execution times out:"
echo "  → You're on free tier (10-second limit)"
echo "  → Upgrade to Vercel Pro for longer timeouts"
echo "  → Keep code execution under 10 seconds"
echo ""
echo ""
echo "Need detailed help? See:"
echo "  - QUICK_START.md    (5-minute version)"
echo "  - DEPLOYMENT.md     (detailed guide)"
echo "  - MIGRATION_GUIDE.md (how we built this)"
