services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: compilador_backend
    privileged: true
    expose:
       - "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DOCKER_HOST=unix:///var/run/docker.sock

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    restart: unless-stopped
    networks:
      - appnet

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: compilador_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
